import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Archive, ArrowUp, AtSign, Bot, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Code2, Command, FilePlus2, FolderOpen, GitBranch, History, LayoutGrid, Menu, MoreHorizontal, Paperclip, PanelLeft, Plus, Search, Settings, Sparkles, Square, Terminal, X, Zap } from 'lucide-react';

type Mode = 'Ask' | 'Plan' | 'Agent' | 'Swarm';
type Message = { id: string; role: 'user' | 'assistant'; text: string; time: string; working?: boolean };

const initialMessages: Message[] = [{ id: 'welcome', role: 'assistant', text: 'I’m ready when you are. Describe what you want to build, review, or fix.', time: 'Now' }];
const prompts = [{ icon: Search, title: 'Explore', body: 'Understand a codebase or find the right approach' }, { icon: Code2, title: 'Build', body: 'Turn an idea into a working feature' }, { icon: Archive, title: 'Review', body: 'Inspect code for quality, risk, and improvements' }, { icon: Zap, title: 'Fix', body: 'Diagnose an issue and get things moving again' }];

function App() {
  const [collapsed, setCollapsed] = useState(false);
  const [mode, setMode] = useState<Mode>('Ask');
  const [composer, setComposer] = useState('');
  const [messages, setMessages] = useState<Message[]>(() => { try { return JSON.parse(localStorage.getItem('altrex-messages') || 'null') || initialMessages; } catch { return initialMessages; } });
  const [running, setRunning] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [project, setProject] = useState('No project open');
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => { localStorage.setItem('altrex-messages', JSON.stringify(messages)); }, [messages]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'n') { event.preventDefault(); setMessages(initialMessages); setComposer(''); inputRef.current?.focus(); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'p') { event.preventDefault(); setShowSearch(true); } if (event.key === 'Escape') { setShowSearch(false); setShowSettings(false); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);

  const send = () => { const text = composer.trim(); if (!text || running) return; const now = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'user', text, time: now }]); setComposer(''); setRunning(true); window.setTimeout(() => { setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'assistant', text: mode === 'Ask' ? 'This preview is connected to the ALTREX interaction shell. Provider execution is not configured yet, so no model result was fabricated.' : `${mode} mode is visible, but desktop execution capabilities are not connected in this preview. Open a project and configure a provider to continue.`, time: 'Now' }]); setRunning(false); }, 650); };
  const currentTitle = messages.find(m => m.role === 'user')?.text || 'New conversation';
  const filtered = useMemo(() => messages.filter(m => m.text.toLowerCase().includes(composer.toLowerCase())), [messages, composer]);

  return <div className="app-shell">
    <aside className={collapsed ? 'sidebar collapsed' : 'sidebar'}>
      <div className="brand"><button className="brand-mark" aria-label="ALTREX home" onClick={() => setMessages(initialMessages)}>A</button>{!collapsed && <span>ALTREX</span>}<button className="icon-button sidebar-toggle" onClick={() => setCollapsed(v => !v)} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronRight size={16}/> : <ChevronLeft size={16}/>}</button></div>
      <div className="side-actions"><button className="side-action primary" onClick={() => { setMessages(initialMessages); inputRef.current?.focus(); }}><Plus size={17}/>{!collapsed && <><span>New chat</span><kbd>⌘ N</kbd></>}</button><button className="side-action" onClick={() => setShowSearch(true)}><Search size={17}/>{!collapsed && <><span>Search</span><kbd>⌘ P</kbd></>}</button><button className="side-action" onClick={() => setProject('Project picker unavailable')}><FolderOpen size={17}/>{!collapsed && <span>Open project</span>}</button></div>
      {!collapsed && <><div className="side-section"><div className="section-label">WORKSPACE</div><div className="workspace-card"><div className="workspace-icon"><Code2 size={16}/></div><div><strong>{project}</strong><small>Local workspace</small></div><MoreHorizontal size={15}/></div></div><div className="side-section history"><div className="section-label"><span>RECENT</span><History size={14}/></div>{messages.some(m => m.role === 'user') ? <button className="history-item"><span className="history-dot"/><span>{currentTitle.slice(0, 29)}{currentTitle.length > 29 ? '…' : ''}</span></button> : <div className="empty-history">No saved conversations yet</div>}</div></>}
      <div className="sidebar-bottom"><button className="side-action" onClick={() => setShowSettings(true)}><Settings size={17}/>{!collapsed && <span>Settings</span>}</button><button className="side-action"><CircleHelp size={17}/>{!collapsed && <span>Help & feedback</span>}</button></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="breadcrumb"><span className="crumb-muted">ALTREX CODE</span><ChevronRight size={13}/><span>{project}</span><ChevronRight size={13}/><strong>{currentTitle}</strong></div><div className="top-actions"><button className="icon-button"><GitBranch size={16}/><span className="branch-label">main</span></button><button className="icon-button" onClick={() => setShowResults(v => !v)}><Activity size={16}/>{showResults && <span className="result-dot"/>}</button><button className="icon-button" onClick={() => setShowSettings(true)}><Settings size={16}/></button><button className="avatar">AL</button></div></header>
      <div className="content-scroll"><section className="conversation">{messages.length === 1 && <div className="home-state"><div className="ai-logo">&lt;/&gt;</div><h1>What should we build?</h1><p>Ask ALTREX to explore, build, review, or fix your code.</p><div className="prompt-grid">{prompts.map(({ icon: Icon, title, body }) => <button className="prompt-card" key={title} onClick={() => { setComposer(`${title}: `); inputRef.current?.focus(); }}><span className="prompt-icon"><Icon size={17}/></span><span><strong>{title}</strong><small>{body}</small></span><ArrowUp size={14}/></button>)}</div></div>}<div className="message-list">{messages.filter(m => m.id !== 'welcome' || messages.length > 1).map(m => <article key={m.id} className={m.role === 'user' ? 'message user-message' : 'message assistant-message'}>{m.role === 'assistant' && <div className="message-avatar"><Code2 size={15}/></div>}<div className="message-body">{m.role === 'user' ? <div className="user-bubble">{m.text}</div> : <><div className="assistant-label">ALTREX <span>{m.time}</span></div><p>{m.text}</p>{m.working && <div className="working"><span className="spinner"/> Working…</div>}</>}</div></article>)}</div></section></div>
      <div className="composer-wrap"><div className="composer"><textarea ref={inputRef} value={composer} onChange={e => setComposer(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); send(); } }} placeholder="Describe what you want to build…" rows={1}/><div className="composer-toolbar"><div className="toolbar-left"><button className="tool-button" title="Add context"><Paperclip size={16}/><span>Add context</span></button><button className="project-pill" onClick={() => setProject('Project picker unavailable')}><FolderOpen size={14}/><span>{project}</span><ChevronDown size={13}/></button></div><div className="toolbar-right"><div className="mode-switch"><button className="mode-button" onClick={() => setMode(mode === 'Ask' ? 'Plan' : 'Ask')}><span className="mode-dot"/> {mode}<ChevronDown size={13}/></button><button className={running ? 'send-button stop' : 'send-button'} onClick={() => running ? setRunning(false) : send()} aria-label={running ? 'Stop' : 'Send'}>{running ? <Square size={14} fill="currentColor"/> : <ArrowUp size={16}/>}</button></div></div></div></div><div className="composer-hint"><span>Enter to send</span><span>Shift + Enter for new line</span><span className="hint-right">ALTREX is still learning your workspace</span></div></div>
    </main>
    {showResults && <aside className="results-panel"><div className="results-header"><div><span className="eyebrow">TASK RESULTS</span><h2>No results yet</h2></div><button className="icon-button" onClick={() => setShowResults(false)}><X size={16}/></button></div><div className="results-empty"><Activity size={22}/><p>Changed files and command output will appear here once a connected agent completes work.</p></div></aside>}
    {showSearch && <div className="modal-backdrop" onMouseDown={() => setShowSearch(false)}><div className="search-dialog" onMouseDown={e => e.stopPropagation()}><div className="search-input"><Search size={18}/><input autoFocus placeholder="Search conversations and commands" value={composer} onChange={e => setComposer(e.target.value)}/><kbd>ESC</kbd></div><div className="search-results">{filtered.length ? filtered.map(m => <div className="search-result" key={m.id}><span>{m.role === 'user' ? 'Prompt' : 'Response'}</span><strong>{m.text}</strong></div>) : <div className="search-empty">No matching conversations</div>}</div></div></div>}
    {showSettings && <div className="modal-backdrop" onMouseDown={() => setShowSettings(false)}><div className="settings-dialog" onMouseDown={e => e.stopPropagation()}><div className="dialog-header"><div><span className="eyebrow">ALTREX CODE</span><h2>Settings</h2></div><button className="icon-button" onClick={() => setShowSettings(false)}><X size={16}/></button></div><div className="settings-list"><div className="setting-row"><span><strong>Provider connection</strong><small>No provider configured in this preview</small></span><button className="outline-button">Configure</button></div><div className="setting-row"><span><strong>Appearance</strong><small>Charcoal · Compact · System theme</small></span><button className="outline-button">System</button></div><div className="setting-row"><span><strong>Permissions</strong><small>Desktop bridge capabilities are unavailable</small></span><span className="status-badge">Protected</span></div></div></div></div>}
  </div>;
}

export default App;

