import { useEffect, useMemo, useRef, useState } from 'react';
import { Activity, Archive, ArrowUp, Bot, Check, ChevronDown, ChevronLeft, ChevronRight, CircleHelp, Code2, Command, FilePlus2, FolderOpen, GitBranch, History, Menu, MoreHorizontal, Paperclip, PanelLeft, Plus, Search, Settings, Sparkles, Square, Terminal, X, Zap } from 'lucide-react';

type Mode = 'Ask' | 'Plan' | 'Agent' | 'Swarm';
type Provider = 'ALTREX Default' | 'Claude 3.7 Sonnet' | 'GPT-4.1' | 'Gemini 2.5 Pro';
type Message = { id: string; role: 'user' | 'assistant'; text: string; time: string; working?: boolean };

type Repo = { name: string; branch: string; source: string };

const initialMessages: Message[] = [{ id: 'welcome', role: 'assistant', text: 'I’m ready when you are. Describe what you want to build, review, or fix.', time: 'Now' }];
const prompts = [{ icon: Search, title: 'Explore', body: 'Understand a codebase or find the right approach' }, { icon: Code2, title: 'Build', body: 'Turn an idea into a working feature' }, { icon: Archive, title: 'Review', body: 'Inspect code for quality, risk, and improvements' }, { icon: Zap, title: 'Fix', body: 'Diagnose an issue and get things moving again' }];
const providers: Provider[] = ['ALTREX Default', 'Claude 3.7 Sonnet', 'GPT-4.1', 'Gemini 2.5 Pro'];

function App() {
  const [collapsed, setCollapsed] = useState(false);
  const [mode, setMode] = useState<Mode>('Ask');
  const [provider, setProvider] = useState<Provider>('ALTREX Default');
  const [composer, setComposer] = useState('');
  const [messages, setMessages] = useState<Message[]>(() => { try { return JSON.parse(localStorage.getItem('altrex-messages') || 'null') || initialMessages; } catch { return initialMessages; } });
  const [running, setRunning] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [showSearch, setShowSearch] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [showModes, setShowModes] = useState(false);
  const [showProviders, setShowProviders] = useState(false);
  const [showProjectPicker, setShowProjectPicker] = useState(false);
  const [toast, setToast] = useState('');
  const [project, setProject] = useState<Repo | null>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => { localStorage.setItem('altrex-messages', JSON.stringify(messages)); }, [messages]);
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(''), 2600); return () => window.clearTimeout(timer); }, [toast]);
  useEffect(() => { const handler = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'n') { event.preventDefault(); resetChat(); } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'p') { event.preventDefault(); setShowSearch(true); } if (event.key === 'Escape') { setShowSearch(false); setShowSettings(false); setShowModes(false); setShowProviders(false); setShowProjectPicker(false); } }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, []);

  const resetChat = () => { setMessages(initialMessages); setComposer(''); inputRef.current?.focus(); setToast('New conversation ready'); };
  const selectProject = (repo: Repo) => { setProject(repo); setShowProjectPicker(false); setToast(`Connected to ${repo.name}`); };
  const cloneRepository = () => { const repo = { name: 'altrex-starter', branch: 'main', source: 'github.com/altrex/starter' }; selectProject(repo); };
  const send = () => { const text = composer.trim(); if (!text || running) return; const now = new Date().toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }); setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'user', text, time: now }]); setComposer(''); setRunning(true); window.setTimeout(() => { setMessages(prev => [...prev, { id: crypto.randomUUID(), role: 'assistant', text: `${mode} mode is active with ${provider}. This preview validates the interaction flow, but provider execution is not configured yet, so no model result was fabricated.`, time: 'Now' }]); setRunning(false); }, 700); };
  const currentTitle = messages.find(m => m.role === 'user')?.text || 'New conversation';
  const filtered = useMemo(() => messages.filter(m => m.text.toLowerCase().includes(composer.toLowerCase())), [messages, composer]);

  return <div className="app-shell" onClick={() => { if (showModes) setShowModes(false); if (showProviders) setShowProviders(false); }}>
    <aside className={collapsed ? 'sidebar collapsed' : 'sidebar'}>
      <div className="brand"><button className="brand-mark" aria-label="ALTREX home" onClick={resetChat}>A</button>{!collapsed && <span>ALTREX</span>}<button className="icon-button sidebar-toggle" onClick={() => setCollapsed(v => !v)} aria-label={collapsed ? 'Expand sidebar' : 'Collapse sidebar'}>{collapsed ? <ChevronRight size={16}/> : <ChevronLeft size={16}/>}</button></div>
      <div className="side-actions"><button className="side-action primary" onClick={resetChat}><Plus size={17}/>{!collapsed && <><span>New chat</span><kbd>⌘ N</kbd></>}</button><button className="side-action" onClick={() => setShowSearch(true)}><Search size={17}/>{!collapsed && <><span>Search</span><kbd>⌘ P</kbd></>}</button><button className="side-action" onClick={() => setShowProjectPicker(true)}><FolderOpen size={17}/>{!collapsed && <span>Open project</span>}</button></div>
      {!collapsed && <><div className="side-section"><div className="section-label">WORKSPACE</div><button className="workspace-card" onClick={() => setShowProjectPicker(true)}><div className="workspace-icon"><Code2 size={16}/></div><div><strong>{project?.name || 'No project open'}</strong><small>{project ? `${project.source} · ${project.branch}` : 'Connect a repository'}</small></div><ChevronRight size={15}/></button></div><div className="side-section history"><div className="section-label"><span>RECENT</span><History size={14}/></div>{messages.some(m => m.role === 'user') ? <button className="history-item"><span className="history-dot"/><span>{currentTitle.slice(0, 29)}{currentTitle.length > 29 ? '…' : ''}</span></button> : <div className="empty-history">No saved conversations yet</div>}</div></>}
      <div className="sidebar-bottom"><button className="side-action" onClick={() => setShowSettings(true)}><Settings size={17}/>{!collapsed && <span>Settings</span>}</button><button className="side-action"><CircleHelp size={17}/>{!collapsed && <span>Help & feedback</span>}</button></div>
    </aside>
    <main className="main-area">
      <header className="topbar"><div className="breadcrumb"><span className="crumb-muted">ALTREX CODE</span><ChevronRight size={13}/><span>{project?.name || 'Workspace'}</span><ChevronRight size={13}/><strong>{currentTitle}</strong></div><div className="top-actions"><button className="branch-button" onClick={() => setToast(`Branch: ${project?.branch || 'main'}`)}><GitBranch size={16}/><span>{project?.branch || 'main'}</span><ChevronDown size={13}/></button><button className="icon-button" onClick={() => setShowResults(v => !v)}><Activity size={16}/>{showResults && <span className="result-dot"/>}</button><button className="icon-button" onClick={() => setShowSettings(true)}><Settings size={16}/></button><button className="avatar">AL</button></div></header>
      <div className="content-scroll"><section className="conversation">{messages.length === 1 && <div className="home-state"><div className="ai-logo"><span className="logo-bracket">&lt;/&gt;</span><span className="logo-pulse"/></div><span className="eyebrow accent-eyebrow">THE AI WORKSPACE FOR BUILDERS</span><h1>What should we build?</h1><p>One focused space to explore, build, review, and ship better software.</p><div className="prompt-grid">{prompts.map(({ icon: Icon, title, body }) => <button className="prompt-card" key={title} onClick={() => { setComposer(`${title}: `); inputRef.current?.focus(); }}><span className="prompt-icon"><Icon size={17}/></span><span><strong>{title}</strong><small>{body}</small></span><ArrowUp size={14}/></button>)}</div></div>}<div className="message-list">{messages.filter(m => m.id !== 'welcome' || messages.length > 1).map(m => <article key={m.id} className={m.role === 'user' ? 'message user-message' : 'message assistant-message'}>{m.role === 'assistant' && <div className="message-avatar"><Code2 size={15}/></div>}<div className="message-body">{m.role === 'user' ? <div className="user-bubble">{m.text}</div> : <><div className="assistant-label">ALTREX <span>{m.time}</span></div><p>{m.text}</p>{m.working && <div className="working"><span className="spinner"/> Working…</div>}</>}</div></article>)}</div></section></div>
      <div className="composer-wrap"><div className="composer"><textarea ref={inputRef} value={composer} onChange={e => setComposer(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); send(); } }} placeholder="Describe what you want to build…" rows={1}/><div className="composer-toolbar"><div className="toolbar-left"><button className="tool-button" title="Add context" onClick={() => setToast('Context attachments are ready for the desktop bridge')}><Paperclip size={16}/><span>Add context</span></button><button className="project-pill" onClick={() => setShowProjectPicker(true)}><FolderOpen size={14}/><span>{project?.name || 'Open project'}</span><ChevronDown size={13}/></button></div><div className="toolbar-right"><div className="mode-switch"><button className="mode-button" onClick={e => { e.stopPropagation(); setShowModes(v => !v); setShowProviders(false); }}><span className="mode-dot"/> {mode}<ChevronDown size={13}/></button>{showModes && <div className="floating-menu mode-menu">{(['Ask', 'Plan', 'Agent', 'Swarm'] as Mode[]).map(item => <button key={item} onClick={() => { setMode(item); setShowModes(false); setToast(`${item} mode selected`); }}><span className="mode-dot"/>{item}{mode === item && <Check size={14}/>}</button>)}</div>}<button className={running ? 'send-button stop' : 'send-button'} onClick={() => running ? (setRunning(false), setToast('Run cancelled')) : send()} aria-label={running ? 'Stop' : 'Send'}>{running ? <Square size={14} fill="currentColor"/> : <ArrowUp size={16}/>}</button></div></div></div><div className="composer-hint"><span>Enter to send</span><span>Shift + Enter for new line</span><button className="provider-selector" onClick={e => { e.stopPropagation(); setShowProviders(v => !v); setShowModes(false); }}><Bot size={13}/>{provider}<ChevronDown size={12}/></button>{showProviders && <div className="floating-menu provider-menu">{providers.map(item => <button key={item} onClick={() => { setProvider(item); setShowProviders(false); setToast(`${item} selected`); }}>{item}{provider === item && <Check size={14}/>}</button>)}</div>}</div></div></div>
    </main>
    {showResults && <aside className="results-panel"><div className="results-header"><div><span className="eyebrow">TASK RESULTS</span><h2>No results yet</h2></div><button className="icon-button" onClick={() => setShowResults(false)}><X size={16}/></button></div><div className="results-empty"><Activity size={22}/><p>Changed files and command output will appear here once a connected agent completes work.</p></div></aside>}
    {showSearch && <div className="modal-backdrop" onMouseDown={() => setShowSearch(false)}><div className="search-dialog" onMouseDown={e => e.stopPropagation()}><div className="search-input"><Search size={18}/><input autoFocus placeholder="Search conversations and commands" value={composer} onChange={e => setComposer(e.target.value)}/><kbd>ESC</kbd></div><div className="search-results">{filtered.length ? filtered.map(m => <div className="search-result" key={m.id}><span>{m.role === 'user' ? 'Prompt' : 'Response'}</span><strong>{m.text}</strong></div>) : <div className="search-empty">No matching conversations</div>}</div></div></div>}
    {showSettings && <div className="modal-backdrop" onMouseDown={() => setShowSettings(false)}><div className="settings-dialog" onMouseDown={e => e.stopPropagation()}><div className="dialog-header"><div><span className="eyebrow">ALTREX CODE</span><h2>Settings</h2></div><button className="icon-button" onClick={() => setShowSettings(false)}><X size={16}/></button></div><div className="settings-list"><div className="setting-row"><span><strong>Provider connection</strong><small>{provider} selected for preview interactions</small></span><button className="outline-button" onClick={() => { setShowSettings(false); setShowProviders(true); }}>Change</button></div><div className="setting-row"><span><strong>Appearance</strong><small>Obsidian · Compact · Motion enabled</small></span><span className="status-badge"><Sparkles size={12}/> Premium</span></div><div className="setting-row"><span><strong>Permissions</strong><small>Desktop bridge capabilities are unavailable</small></span><span className="status-badge">Protected</span></div></div></div></div>}
    {showProjectPicker && <div className="modal-backdrop" onMouseDown={() => setShowProjectPicker(false)}><div className="project-dialog" onMouseDown={e => e.stopPropagation()}><div className="dialog-header"><div><span className="eyebrow">WORKSPACE</span><h2>Connect a project</h2></div><button className="icon-button" onClick={() => setShowProjectPicker(false)}><X size={16}/></button></div><div className="repo-option"><div className="repo-icon"><GitBranch size={18}/></div><div><strong>Clone from GitHub</strong><small>Connect a repository to enable workspace context.</small></div><button className="outline-button" onClick={cloneRepository}>Clone</button></div><div className="repo-option"><div className="repo-icon"><FolderOpen size={18}/></div><div><strong>Open local folder</strong><small>Desktop bridge permission required in this preview.</small></div><button className="outline-button" onClick={() => setToast('Local folders require the ALTREX desktop app')}>Open</button></div></div></div>}
    {toast && <div className="toast"><Check size={14}/>{toast}</div>}
  </div>;
}

export default App;
